/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:b208ddd5-e22f-4d20-8257-ced9f6c14168",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_W2CN8YLTB",
    "aws_user_pools_web_client_id": "1d57rle28tabt21e49b4063iqp",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "xapo-s3-client-uploads224232-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_content_delivery_bucket": "xapo-s3-client-uploads-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "https://d3ll6zbfabpmex.cloudfront.net"
};


export default awsmobile;
